FROM debian:stable-slim AS build-env

# FROM frolvlad/alpine-glibc
FROM gcr.io/distroless/base

# RUN apk update && apk add libstdc++

COPY --from=build-env /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/libz.so.1

EXPOSE 8080
COPY target/rest-service-demo app
ENTRYPOINT ["/app"]

# Build and run:
# docker build -f ./Dockerfile.distroless -t localhost/rest-service-demo:distroless .
# docker run --rm -p 8080:8080 localhost/rest-service-demo:distroless