FROM container-registry.oracle.com/java/openjdk:17-oraclelinux8

EXPOSE 8080
COPY target/rest-service-demo-0.0.1-SNAPSHOT-exec.jar app.jar
CMD ["java","-jar","app.jar"]

# Build and run:
# docker build -f ./Dockerfile.jvm -t localhost/rest-service-demo:jvm
# docker run --rm -p 8080:8080 localhost/rest-service-demo:jvm